-- products.cars definition

CREATE TABLE cars (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `make` varchar(135) NOT NULL,
  `model` varchar(135) NOT NULL,
  `variant` varchar(45) NOT NULL,
  `price` REAL NOT NULL,
  `seats` INTEGER NOT NULL,
  `year` INTEGER NOT NULL,
  `body_type` varchar(45) NOT NULL,
  `body_length` INTEGER NOT NULL,
  `body_width` INTEGER NOT NULL,
  `body_height` INTEGER NOT NULL,
  `body_wheel_base` INTEGER NOT NULL,
  `body_wheel_size` INTEGER NOT NULL,
  `body_ground_clearance` INTEGER NOT NULL,
  `transmission_type` varchar(45) NOT NULL,
  `transmission_gears` INTEGER,
  `safety_ncap` INTEGER,
  `safety_airbags` INTEGER,
  `engine_type` varchar(45) NOT NULL,
  `engine_displacement` REAL NOT NULL,
  `engine_hp` INTEGER NOT NULL,
  `engine_torque` INTEGER NOT NULL,
  `engine_time0to100` INTEGER NOT NULL,
  `fuel_type` varchar(45) NOT NULL,
  `kmpl_city` REAL NOT NULL,
  `kmpl_highway` REAL NOT NULL,
  `full_tank_drive_capacity` INTEGER NOT NULL,
  `drivetrain_type` varchar(45) NOT NULL,
  `feature_sunroof` INTEGER NOT NULL DEFAULT 0,
  `feature_ventilated_seats` INTEGER NOT NULL DEFAULT 0,
  `feature_wireless_charger` INTEGER NOT NULL DEFAULT 0,
  `feature_reverse_camera` INTEGER NOT NULL DEFAULT 0,
  `feature_view360` INTEGER NOT NULL DEFAULT 0,
  `feature_watch_connect` INTEGER NOT NULL DEFAULT 0,
  `infotainment_available` INTEGER NOT NULL DEFAULT 0,
  `infotainment_size` INTEGER NOT NULL,
  `infotainment_android` INTEGER NOT NULL DEFAULT 0,
  `infotainment_apple` INTEGER NOT NULL DEFAULT 0,
  `aesthetic_noise` INTEGER NOT NULL,
  `aesthetic_leg_space` INTEGER NOT NULL,
  `expense_ppk` INTEGER NOT NULL,
  `expense_insurance` INTEGER NOT NULL,
  `expense_service` INTEGER NOT NULL,
  `expense_service_frequency` INTEGER NOT NULL,
  `url` varchar(255),
  `mrp` integer NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `validation_status` varchar(45) NOT NULL,
  `version` varchar(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (name)
);

