-- products.cars definition

CREATE TABLE `cars` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(135) NOT NULL,
  `make` varchar(45) NOT NULL,
  `model` varchar(45) NOT NULL,
  `variant` varchar(45) NOT NULL,
  `price` decimal(10,2) unsigned NOT NULL,
  `seats` tinyint unsigned NOT NULL,
  `year` smallint unsigned NOT NULL,
  `body_type` varchar(45) NOT NULL,
  `body_length` smallint unsigned NOT NULL COMMENT 'In mm',
  `body_width` smallint unsigned NOT NULL COMMENT 'In mm',
  `body_height` smallint unsigned NOT NULL COMMENT 'In mm',
  `body_wheel_base` smallint unsigned NOT NULL COMMENT 'In mm',
  `body_wheel_size` smallint unsigned NOT NULL COMMENT 'In mm',
  `body_ground_clearance` smallint unsigned NOT NULL COMMENT 'In mm',
  `transmission_type` varchar(45) NOT NULL,
  `transmission_gears` tinyint unsigned DEFAULT NULL,
  `safety_ncap` tinyint DEFAULT NULL,
  `safety_airbags` tinyint DEFAULT NULL,
  `engine_type` varchar(45) NOT NULL,
  `engine_displacement` decimal(4,1) NOT NULL,
  `engine_hp` smallint unsigned NOT NULL,
  `engine_torque` smallint unsigned NOT NULL,
  `engine_time0to100` tinyint unsigned NOT NULL,
  `fuel_type` varchar(45) NOT NULL,
  `kmpl_city` decimal(4,1) unsigned NOT NULL,
  `kmpl_highway` decimal(4,1) unsigned NOT NULL,
  `full_tank_drive_capacity` smallint unsigned NOT NULL,
  `drivetrain_type` varchar(3) NOT NULL,
  `feature_sunroof` tinyint(1) NOT NULL DEFAULT '0',
  `feature_ventilated_seats` tinyint(1) NOT NULL DEFAULT '0',
  `feature_wireless_charger` tinyint(1) NOT NULL DEFAULT '0',
  `feature_reverse_camera` tinyint(1) NOT NULL DEFAULT '0',
  `feature_view360` tinyint(1) NOT NULL DEFAULT '0',
  `feature_watch_connect` tinyint(1) NOT NULL DEFAULT '0',
  `infotainment_available` tinyint(1) NOT NULL DEFAULT '0',
  `infotainment_size` tinyint NOT NULL,
  `infotainment_android` tinyint(1) NOT NULL DEFAULT '0',
  `infotainment_apple` tinyint(1) NOT NULL DEFAULT '0',
  `aesthetic_noise` tinyint unsigned NOT NULL,
  `aesthetic_leg_space` smallint unsigned NOT NULL,
  `expense_ppk` tinyint unsigned NOT NULL,
  `expense_insurance` mediumint unsigned NOT NULL,
  `expense_service` mediumint unsigned NOT NULL,
  `expense_service_frequency` tinyint unsigned NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=29201 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;