-- products.mobiles definition (SQLite)

CREATE TABLE `mobiles` (
    `id` varchar(255) NOT NULL,
    `name` varchar(135) NOT NULL,
    `make` varchar(45) NOT NULL,
    `model` varchar(45) NOT NULL,
    `variant` varchar(45) NOT NULL,
    `year` integer NOT NULL,
    `price` decimal(10,2) NOT NULL,
    `mrp` decimal(10,2) DEFAULT NULL,
    `url` varchar(255) DEFAULT NULL,
    `official_buy_url` varchar(255) DEFAULT NULL,
    `value_for_money` decimal(2,1),
    `after_sales_service` decimal(2,1),
    `battery_life_usage` integer NOT NULL,
    `battery_life_standby` integer NOT NULL,
    `battery_life_talk_time` integer NOT NULL,
    `battery_life_gaming` integer NOT NULL,
    `battery_life_video_playback` integer NOT NULL,
    `battery_capacity` integer NOT NULL,
    `battery_charging_wired` integer NOT NULL,
    `battery_charging_wireless` integer NOT NULL,
    `battery_reverse_charging` integer NOT NULL DEFAULT 0,
    `battery_removable` integer NOT NULL DEFAULT 0,
    `battery_charging_time_wired` integer NOT NULL,
    `battery_charging_time_wireless` integer NOT NULL DEFAULT 0,
    `cameras_main_megapixel` integer NOT NULL,
    `cameras_main_aperture` varchar(45) NOT NULL,
    `cameras_main_focal_length` integer NOT NULL,
    `cameras_main_optical_zoom` integer NOT NULL,
    `cameras_main_digital_zoom` integer NOT NULL,
    `cameras_front_megapixel` integer NOT NULL,
    `cameras_front_focal_length` integer NOT NULL,
    `cameras_front_type` varchar(45) NOT NULL,
    `cameras_front_aperture` varchar(45) NOT NULL,
    `connectivity_sim_count` integer NOT NULL,
    `features_face_unlock` integer NOT NULL DEFAULT 0,
    `features_fingerprint_sensor` integer NOT NULL DEFAULT 0,
    `features_always_on_display` integer NOT NULL DEFAULT 0,
    `features_de_x_support` integer NOT NULL DEFAULT 0,
    `features_stylus_support` integer NOT NULL DEFAULT 0,
    `features_fast_charging` integer NOT NULL DEFAULT 0,
    `features_reverse_charging` integer NOT NULL DEFAULT 0,
    `features_audio_jack` integer NOT NULL DEFAULT 0,
    `features_stereo_speakers` integer NOT NULL DEFAULT 0,
    `features_hi_res_audio` integer NOT NULL DEFAULT 0,
    `features_gps` integer NOT NULL DEFAULT 0,
    `features_nfc` integer NOT NULL DEFAULT 0,
    `features_infrared` integer NOT NULL DEFAULT 0,
    `features_support5g` integer NOT NULL DEFAULT 0,
    `features_wifi` integer NOT NULL DEFAULT 0,
    `features_bluetooth` integer NOT NULL DEFAULT 0,
    `features_usb` integer NOT NULL DEFAULT 0,
    `features_water_resistance` integer NOT NULL DEFAULT 0,
    `features_e_sim` integer NOT NULL DEFAULT 0,
    `display_type` varchar(45) NOT NULL,
    `display_size` integer NOT NULL,
    `display_resolution_width` integer NOT NULL,
    `display_resolution_height` integer NOT NULL,
    `display_refresh_rate` integer NOT NULL,
    `display_brightness` integer NOT NULL,
    `dimensions_height` integer NOT NULL,
    `dimensions_width` integer NOT NULL,
    `dimensions_thickness` integer NOT NULL,
    `dimensions_weight` integer NOT NULL,
    `display_screen_to_body_ratio` integer NOT NULL,
    `error_message` varchar(255) NOT NULL,
    `platform_os` varchar(45) NOT NULL,
    `platform_os_version` varchar(10) NOT NULL,
    `memory_ram` integer NOT NULL,
    `mrp` integer NOT NULL,
    `memory_storage` integer NOT NULL,
    `memory_expandable` integer NOT NULL DEFAULT 0,
    `memory_storage_type` varchar(45) NOT NULL,
    `official_buy_url` varchar(45) NOT NULL,
    `validation_status` varchar(45) NOT NULL,
    `version` varchar(45) NOT NULL,
    `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`name`)
);

